language: node_js
node_js: 
  - "6"

# Travis-CI Caching
cache:
  directories:
    - node_modules


# S: Build Lifecycle
install:
  - npm install

before_script:
 # - npm install -g vue-cli


script:

after_script:
  - npm run build
  - cd dist
  - git init
  - git config user.name "yimo"
  - git config user.email "1280160831@qq.com"
  - git add *
  - git commit -m "Update blogs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/yimogit/metools.git
