language: node_js
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules


# S: Build Lifecycle
install:
  - npm install

before_script:
 # - npm install -g gulp


script:
  - npm run build


after_script:
  - rm ./dist /s /q
  - mkdir dist
  - cd ./dist
  - git init
  - git config user.name "yimo"
  - git config user.email "1280160831@qq.com"
  - git add .
  - git commit -m "Update blogs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" [gh-pages]:[gh-pages]
# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/yimogit/metools.git
